[config]
layout = "cookbook"
toc = true
colab = "https://colab.research.google.com/github/deepset-ai/haystack-cookbook/blob/main/notebooks/"

[[cookbook]]
title = "PDF-Based Question Answering with Amazon Bedrock and Haystack"
notebook = "amazon_bedrock_for_documentation_qa.ipynb"
topics = ["RAG"]

[[cookbook]]
title = "Question Answering with Amazon Sagemaker, Chroma and Haystack"
notebook = "amazon_sagemaker_and_chroma_for_qa.ipynb"
topics = ["RAG"]

[[cookbook]]
title = "RAG: Extract and use website content for question answering with Apify-Haystack integration"
notebook = "apify_haystack_rag.ipynb"
topics = ["RAG", "Web-QA"]

[[cookbook]]
title = "AstraDB ü§ù Haystack Integration"
notebook = "astradb_haystack_integration.ipynb"
topics = ["RAG"]

[[cookbook]]
title = "Improving Retrieval with Auto-Merging and Hierarchical Document Retrieval"
notebook = "auto_merging_retriever.ipynb"
topics = ["Advanced Retrieval", "RAG"]
experimental = true
discuss = "https://github.com/deepset-ai/haystack-experimental/discussions/78"

[[cookbook]]
title = "üß© Quizzes and Adventures üè∞ with Character Codex and llamafile"
notebook = "charactercodex_llamafile.ipynb"
topics = ["Model Serving", "Chat"]

[[cookbook]]
title = "Chat With Your SQL Database"
notebook = "chat_with_SQL_3_ways.ipynb"
topics = ["Chat", "SQL", "Agents"]

[[cookbook]]
title = "Chroma Indexing and RAG Examples"
notebook = "chroma-indexing-and-rag-examples.ipynb"
topics = ["RAG", "Vector Databases"]

[[cookbook]]
title = "Cohere v3 for Multilingual QA"
notebook = "cohere-v3-for-multilingual-qa.ipynb"
topics = ["Multilingual RAG"]

[[cookbook]]
title = "Run Tasks Concurrently Within a Custom Component"
notebook = "concurrent_tasks.ipynb"
topics = ["Customization"]
experimental = true

[[cookbook]]
title = "Conversational RAG using Memory"
notebook = "conversational_rag_using_memory.ipynb"
topics = ["Chat", "RAG", "Agents"]
experimental = true
discuss = "https://github.com/deepset-ai/haystack-experimental/discussions/75"

[[cookbook]]
title = "Extract Metadata Filters from a Query"
notebook = "extracting_metadata_filters_from_a_user_query.ipynb"
topics = ["Advanced Retrieval", "Metadata"]

[[cookbook]]
title = "Function Calling with OpenAIChatGenerator"
notebook = "function_calling_with_OpenAIChatGenerator.ipynb"
topics = ["Function Calling", "Chat", "Agents"]
outdated = true

[[cookbook]]
title = "Build with Gemma and Haystack"
notebook = "gemma_chat_rag.ipynb"
topics = ["RAG"]

[[cookbook]]
title = "Notion RAG with Gradient Models"
notebook = "gradient-embeders-and-generators-for-notion-rag.ipynb"
topics = ["RAG"]
hidden = true

[[cookbook]]
title = "Hacker News Summaries with Custom Components"
notebook = "hackernews-custom-component-rag.ipynb"
topics = ["RAG", "Customization"]

[[cookbook]]
title = "Hybrid Retrieval with BM42"
notebook = "hybrid_retrieval_bm42.ipynb"
topics = ["Advanced Retrieval"]

[[cookbook]]
title = "Improve Retrieval by Embedding Meaningful Metadata"
notebook = "improve-retrieval-by-embedding-metadata.ipynb"
topics = ["Advanced Retrieval", "Metadata"]

[[cookbook]]
title = "üê¶‚Äç‚¨õ Information Extraction with Raven"
notebook = "information_extraction_raven.ipynb"
topics = ["Function Calling"]

[[cookbook]]
title = "ü¶ç Information Extraction with Gorilla"
notebook = "information-extraction-gorilla.ipynb"
topics = ["Function Calling"]

[[cookbook]]
title = "Legal Document Analysis with jina-embeddings-v2-base-en"
notebook = "jina-embeddings-v2-legal-analysis-rag.ipynb"
topics = ["Summarization", "Advanced Retrieval"]

[[cookbook]]
title = "RAG with Llama 3.1"
notebook = "llama3_rag.ipynb"
topics = ["RAG"]

[[cookbook]]
title = "Web QA with Mixtral-8x7B-Instruct-v0.1"
notebook = "mixtral-8x7b-for-web-qa.ipynb"
topics = ["Web-QA"]

[[cookbook]]
title = "Streaming Model Explorer"
notebook = "model_explorer_streaming.ipynb"
topics = ["Discovery"]

[[cookbook]]
title = "Multilingual RAG on a Podcast"
notebook = "multilingual_rag_podcast.ipynb"
topics = ["Audio", "Multilingual RAG"]

[[cookbook]]
title = "Invoking APIs with OpenAPITool"
notebook = "openapitool.ipynb"
topics = ["Function Calling"]
experimental = true
outdated = true
discuss = "https://github.com/deepset-ai/haystack-experimental/discussions/79"

[[cookbook]]
title = "RAG Evaluation with Prometheus 2"
notebook = "prometheus2_evaluation.ipynb"
topics = ["Evaluation"]

[[cookbook]]
title = "Advanced Prompt Customization for Anthropic"
notebook = "prompt_customization_for_Anthropic.ipynb"
topics = ["Customization", "Prompting"]

[[cookbook]]
title = "Prompt Optimization with DSPy"
notebook = "prompt_optimization_with_dspy.ipynb"
topics = ["Customization", "Prompting"]

[[cookbook]]
title = "Advanced RAG: Query Expansion"
notebook = "query-expansion.ipynb"
topics = ["Advanced Retrieval", "RAG"]

[[cookbook]]
title = "RAG Pipeline Evaluation Using DeepEval"
notebook = "rag_eval_deep_eval.ipynb"
topics = ["Evaluation"]

[[cookbook]]
title = "RAG Pipeline Evaluation Using RAGAS"
notebook = "rag_eval_ragas.ipynb"
topics = ["Evaluation"]

[[cookbook]]
title = "RAG Pipeline Evaluation Using UpTrain"
notebook = "rag_eval_uptrain.ipynb"
topics = ["Evaluation"]

[[cookbook]]
title = "RAG Pipeline Using FastEmbed for Embeddings Generationn"
notebook = "rag_fastembed.ipynb"
topics = ["RAG", "Advanced Retrieval"]

[[cookbook]]
title = "Haystack RAG Pipeline with Self-Deployed AI models using NVIDIA NIMs"
notebook = "rag-with-nims.ipynb"
topics = ["RAG", "Model Serving"]

[[cookbook]]
title = "Sparse Embedding Retrieval with Qdrant and FastEmbed"
notebook = "sparse_embedding_retrieval.ipynb"
topics = ["RAG", "Advanced Retrieval"]

[[cookbook]]
title = "Getting a Daily Digest From Tech Websites"
notebook = "techcrunch_news_digest_titanml_takeoff.ipynb"
topics = ["Model Serving", "RAG"]

[[cookbook]]
title = "Using Hypothetical Document Embeddinga (HyDE) to Improve Retrieval"
notebook = "using_hyde_for_improved_retrieval.ipynb"
topics = ["Advanced Retrieval", "RAG"]

[[cookbook]]
title = "Speaker Diarization with AssemblyAI"
notebook = "using_speaker_diarization_with_assemblyai.ipynb"
topics = ["Audio"]

[[cookbook]]
title = "Function Calling and Multimodal QA with Gemini"
notebook = "vertexai-gemini-examples.ipynb"
topics = ["Function Calling", "Multimodal"]

[[cookbook]]
title = "Use the ‚ö° vLLM inference engine with Haystack"
notebook = "vllm_inference_engine.ipynb"
topics = ["Model Serving"]

[[cookbook]]
title = "ü™Å RAG pipelines with Haystack + Zephyr 7B Beta"
notebook = "zephyr-7b-beta-for-rag.ipynb"
topics = ["RAG"]

[[cookbook]]
title = "Advanced RAG: Query Decomposition and Reasoning"
notebook = "query_decomposition.ipynb"
topics = ["Advanced Retrieval", "RAG", "Agents"]

[[cookbook]]
title = "Analyze Your Instagram Comments‚Äô Vibe with Apify and Haystack"
notebook = "apify_haystack_instagram_comments_analysis.ipynb"
topics = ["Prompting", "Data Scraping"]

[[cookbook]]
title = "Define & Run Tools "
notebook = "tools_support.ipynb"
topics = ["Function Calling", "Chat", "Agents"]
experimental = true
discuss = "https://github.com/deepset-ai/haystack-experimental/discussions/98"

[[cookbook]]
title = "Agentic RAG with Llama 3.2 3B"
notebook = "llama32_agentic_rag.ipynb"
topics = ["RAG", "Agents", "Web-QA"]

[[cookbook]]
title = "Advanced RAG: Automated Structured Metadata Enrichment"
notebook = "metadata_enrichment.ipynb"
topics = ["Advanced Retrieval", "RAG", "Metadata"]

[[cookbook]]
title = "Newsletter Sending Agent with Tools"
notebook = "newsletter-agent.ipynb"
new = true
topics = ["Function Calling", "Chat", "Agents"]

[[cookbook]]
title = "Evaluating AI with Haystack"
notebook = "evaluating_ai_with_haystack.ipynb"
experimental = true
topics = ["Evaluation"]
discuss = "https://github.com/deepset-ai/haystack-experimental/discussions/74"

[[cookbook]]
title = "Multimodal Agent with fastRAG and Haystack"
notebook = "multimodal_agent_with_fastrag_haystack.ipynb"
new = true
topics = ["Multimodal", "Agents"]

[[cookbook]]
title = "Web-Enhanced Self-Reflecting Agent"
notebook = "web_enhanced_self_reflecting_agent.ipynb"
topics = ["Agents"]

[[cookbook]]
title = "Create a Swarm of Agents"
notebook = "swarm.ipynb"
new = true
topics = ["Function Calling", "Chat", "Agents"]

[[cookbook]]
title = "Running Haystack Pipelines in Asynchronous Environments"
notebook = "async_pipeline.ipynb"
new = true
topics = ["Async"]

[[cookbook]]
title = "RAG: Web Search and Analysis with Apify and Haystack"
notebook = "apify_haystack_rag_web_browser.ipynb"
topics = ["Web-QA", "Data Scraping", "RAG"]

[[cookbook]]
title = "Build a GitHub Issue Resolver Agent"
notebook = "github_issue_resolver_agent.ipynb"
new = true
experimental = true
topics = ["Function Calling", "Agents"]
discuss = "https://github.com/deepset-ai/haystack-experimental/discussions/209"

[[cookbook]]
title = "Extracting Metadata with an LLM"
notebook = "metadata_extraction_with_llm_metadata_extractor.ipynb"
new = true
topics = ["Metadata"]
